### ISSUE TITLE
I try joining on alt accounts

### ISSUE THREAD

**Issue by bosshaw** [Aliucord/ban-appeals#18]
### Discord Account

Kazzy#0820

### Why were you banned?

Automatically on join

### Secured Account

- [ ] I have secured my account

### Reason for making a new Account

Because i didn't know if this was safe

**Comment by bosshaw** [comment]
@Juby210 can you please help?

**Comment by bosshaw** [comment]
@Vendicated

**Comment by Vendicated** [comment]
don't join on alt accounts
